### ISSUE TITLE
Auto-generated alerts cannot be deleted

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#358] opened 2024-12-25 09:30 UTC
It would appear that the auto-generated alerts cannot be deleted. Silencing them instead for 10 years is a viable workaround, but it would be nice to have a fix instead of relying on a workaround.

**Comment by oblitorum** [comment] 2024-12-28 17:43
OK, turns out the problem is actually that you must define a group for grafana alert rules. I used the instance name as the group name, so alerts for same instance will be in the same group.

<img width="1198" alt="Screenshot 2024-12-29 at 01 41 47" src="https://github.com/user-attachments/assets/98275d69-4b2f-45a9-97ea-4de19bb4a5b6" />


<img width="1190" alt="image" src="https://github.com/user-attachments/assets/c75f17d6-aa7f-4b9b-bfbb-4bbc28568150" />

**Comment by gordan-bobic** [comment] 2024-12-28 17:48
Oh, interesting. That's really obscure, well done for figuring it out. :-)

**Closed as completed** 2024-12-28 17:49 UTC
Labels: bug
